workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: 3.29.2  # Specify Flutter version
      xcode: 15.0       # Use the latest Xcode version
    scripts:
      - name: Set iOS deployment target
        script: |
          cd ios
          sed -i '' 's/platform :ios, '12.0'/platform :ios, '13.0'/g' Podfile
          cd ..
      - flutter clean
      - flutter pub get
      - cd ios && pod install && cd ..
    artifacts:
      - build/ios/ipa/**/*.ipa




