scripts:
  - name: Set iOS deployment target
    script: |
      cd ios
      sed -i '' 's/platform :ios, '12.0'/platform :ios, '13.0'/g' Podfile
      cd ..
  - flutter clean
  - flutter pub get
  - cd ios && pod install && cd ..
