workflows:
  android-build:
    name: Android Build
    environment:
      flutter: "3.29.2"  # Specify the Flutter version you have
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release




