// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4TICmoQame9kCaTeT3-DIT-7zMLAj3xI',
    appId: '1:686335822745:web:424809e65413f57fdde108',
    messagingSenderId: '686335822745',
    projectId: 'insurancedongle-18b94',
    authDomain: 'insurancedongle-18b94.firebaseapp.com',
    databaseURL: 'https://insurancedongle-18b94-default-rtdb.firebaseio.com',
    storageBucket: 'insurancedongle-18b94.firebasestorage.app',
    measurementId: 'G-LVPMS4LSV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5brE2jP7D6RGmFko_UzKhr44s5zpIbZY',
    appId: '1:686335822745:android:a5638ad4a6a7f52bdde108',
    messagingSenderId: '686335822745',
    projectId: 'insurancedongle-18b94',
    databaseURL: 'https://insurancedongle-18b94-default-rtdb.firebaseio.com',
    storageBucket: 'insurancedongle-18b94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCTkQW7eaRJQF97rlSFmLnYt9ybuATWg',
    appId: '1:686335822745:ios:af902101e1d3c579dde108',
    messagingSenderId: '686335822745',
    projectId: 'insurancedongle-18b94',
    databaseURL: 'https://insurancedongle-18b94-default-rtdb.firebaseio.com',
    storageBucket: 'insurancedongle-18b94.firebasestorage.app',
    iosBundleId: 'com.example.insurancedongle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdCTkQW7eaRJQF97rlSFmLnYt9ybuATWg',
    appId: '1:686335822745:ios:af902101e1d3c579dde108',
    messagingSenderId: '686335822745',
    projectId: 'insurancedongle-18b94',
    databaseURL: 'https://insurancedongle-18b94-default-rtdb.firebaseio.com',
    storageBucket: 'insurancedongle-18b94.firebasestorage.app',
    iosBundleId: 'com.example.insurancedongle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4TICmoQame9kCaTeT3-DIT-7zMLAj3xI',
    appId: '1:686335822745:web:73d0519dc2f99836dde108',
    messagingSenderId: '686335822745',
    projectId: 'insurancedongle-18b94',
    authDomain: 'insurancedongle-18b94.firebaseapp.com',
    databaseURL: 'https://insurancedongle-18b94-default-rtdb.firebaseio.com',
    storageBucket: 'insurancedongle-18b94.firebasestorage.app',
    measurementId: 'G-WFP9BE7L6R',
  );

}